plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.microsoft.sqlserver:mssql-jdbc:12.6.1.jre11'
    implementation 'org.apache.poi:poi-ooxml:5.2.5'
    runtimeOnly 'org.apache.logging.log4j:log4j-core:2.21.1'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

application {
    mainClass = 'com.example.report.Main'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

distributions {
    main {
        contents {
            from('config') {
                into 'config'
            }
            from('run-report.bat') {
                into ''
            }
        }
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
