plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.microsoft.sqlserver:mssql-jdbc:12.6.1.jre11'
}

application {
    mainClass = 'com.example.report.Main'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

distributions {
    main {
        contents {
            from('config') {
                into 'config'
            }
            from('run-report.bat') {
                into ''
            }
        }
    }
}
